apiVersion: v1
kind: Service
metadata:
  name: fastapi-simple-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fastapi-simple
